# File: .github/workflows/repo-sync.yml
on:
  push:
  schedule:
  - cron:  "0 5 */7 * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2.3.0
      with:
        source_repo: "https://github.com/mgsweet/Apex-NoRecoil-2021.git"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.PAT }}
